#!/bin/bash
# Run without sbatch

nProcs=8		# Number of processors used for simpleFoam

. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions

pwd

./Allclean

cp -r 0.orig/ 0

runApplication surfaceFeatureExtract

runApplication blockMesh

runApplication decomposePar

mpirun -np $nProcs snappyHexMesh -parallel -overwrite

restore0Dir -processor

# Test polling interface
runParallel $(getApplication) -opt-switch nPollProcInterfaces=-1

runApplication reconstructPar

#------------------------------------------------------------------------------

touch must.foam