#!/bin/bash
# Run without sbatch

. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions

# Run solver
runParallel $(getApplication) -opt-switch nPollProcInterfaces=-1


# Fix ProcAdressing files
nProcs=$(getNumberOfProcessors)

for ((i = 0; i < $nProcs; i++ )); do
    echo "Copying ProcAdressing files in processor$i/"

    for dir in ./processor$i/[0-9]*/ ;  do
        echo "Copying to $dir"
        mkdir -p $dir/polyMesh
        cp ./processor$i/2/polyMesh/* $dir/polyMesh/
    done
done

runApplication reconstructParMesh -time 2:
runApplication reconstructPar -time 2:

#------------------------------------------------------------------------------

touch must.foam