#!/bin/bash
. ~/.bin/run_of/RunFunctions

# Run solver
runParallel $(getApplication) -opt-switch nPollProcInterfaces=-1

# Reconstruct
runApplication reconstructParMesh -time 1:
runApplication reconstructPar -time 1:

touch must.foam