#!/bin/sh
. ${FOAM_INST_DIR}/OpenFOAM-v2506/bin/tools/CleanFunctions
#------------------------------------------------------------------------------

cleanCase0

rm -rf constant/extendedFeatureEdgeMesh
rm -rf constant/polyMesh
rm constant/triSurface/*.eMesh

#------------------------------------------------------------------------------
