#!/bin/bash

#SBATCH --job-name="RANS-MUST"    # Name of the job for checking
#SBATCH --time=4:00:00                 # Wall clock time requested
#SBATCH --partition=compute-p2          # Which partition?
#SBATCH --account=research-ceg-gse      # Account to charge
#SBATCH --tasks=64                      # Number of tasks
#SBATCH --cpus-per-task=1               # Number of cpu per task
#SBATCH --mem-per-cpu=4000M                      # Ask for memory

module load 2024r1 openmpi
module load openfoam/2306

. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions

# Run solver
nProcs=$(getNumberOfProcessors)
mpirun -np $nProcs simpleFoam -parallel >> log.simpleFoam

# Fix ProcAdressing files
for ((i = 0; i < $nProcs; i++ )); do
    echo "Copying ProcAdressing files in processor$i/"

    for dir in ./processor$i/[0-9]*/ ;  do
        echo "Copying to $dir"
        mkdir -p $dir/polyMesh
        cp ./processor$i/2/polyMesh/* $dir/polyMesh/
    done
done

reconstructParMesh -time 2: >> log.reconstructParMesh
reconstructPar -time 2: >> log.reconstructPar

#------------------------------------------------------------------------------

touch must.foam

squeue -j $SLURM_JOBID
echo "-------- Efficiency ---------"
seff $SLURM_JOBID
