#!/bin/bash
. ~/.bin/run_of/RunFunctions

nProcs=$(getNumberOfProcessors)

cp -r 0.orig/ 0

runApplication surfaceFeatureExtract

m4 system/blockMeshDict.m4 > system/blockMeshDict
runApplication blockMesh

runApplication snappyHexMesh -overwrite

runApplication decomposePar -force

touch must.foam