#!/bin/bash
# Run only meshing

. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions

nProcs=$1		# Number of processors used for simpleFoam

cp -r 0.orig/ 0

runApplication surfaceFeatureExtract

runApplication blockMesh

runApplication decomposePar

mpirun -np $nProcs snappyHexMesh -parallel > log.snappyHexMesh

touch must.foam